### ISSUE TITLE
Função Bascara

### ISSUE THREAD

**Issue by Projetos-IDE** [Projetos-IDE/Teste-de-git-#1]
Implementar Bascara.

Imagem com a função de bascara: https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.educamaisbrasil.com.br%2Fcontent%2Fbanco_de_imagens%2Fguia-de-estudo%2FD%2Fformula-bhaskara-positivo-matematica.jpg&imgrefurl=https%3A%2F%2Fwww.educamaisbrasil.com.br%2Fenem%2Fmatematica%2Fformula-de-bhaskara&tbnid=M2OvrMKzALNfzM&vet=12ahUKEwj1vrXC1sv2AhVxA7kGHbjCC3AQMygIegUIARDOAQ..i&docid=HKAOVsHEadC74M&w=360&h=155&q=Imagem%20com%20a%20fun%C3%A7%C3%A3o%20de%20bhaskara&ved=2ahUKEwj1vrXC1sv2AhVxA7kGHbjCC3AQMygIegUIARDOAQ

**Comment by Projetos-IDE** [comment]
Devo fazer só bascara positiva?

**Comment by Projetos-IDE** [comment]
Não envia um vetor com soma e subtração do delta

**Comment by LeoAlles** [comment]
Nem tinha pensado nisso !
